version: '3.8'

services:
  backend:
    build: ./backend
    ports:
       - "3000:3000"
    environment:
       - MONGO_URL=mongodb://mongo:27017/blogdb
       - SECRET_KEY="add_secret_key"
    depends_on:
       - mongo


  mongo:
    image: mongo:7
    restart: always
    ports:
       - "27017:27017"
    volumes:
       - mongo_data:/data/db

  frontend:
    build: ./frontend
    ports: 
      - "5173:5173"
    depends_on:
      - backend


volumes:
  mongo_data:
